version :"3.9"

services:
  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8001:8000"

  weight-service:
    build: ./weight-service
    container_name: weight-service
    ports:
      - "8002:8000"
