include:
  - ./Weight_service/docker-compose.yml
#  - ./Billing-service/docker-compose.yml
services:
  test-runner:
    build: ./tests
    container_name: test-runner
    depends_on:
    - weight-app
    - weight-db
    # - billing-app
    # - billing-db

  
    volumes:
      - ./tests:/tests
    command: pytest /tests -v


