include:
  - ./weight-service/docker-compose.yml
  - ./billing-service/docker-compose.yml
  #- docker-compose.yaml
services:
  test-runner:
    build: ./tests
    container_name: test-runner
    depends_on:
    - weight-app
    - weight-db
    - billing-service
    - db #billing db name

  
    volumes:
      - ./tests:/tests
    command: ./tests/init.sh
  
      

