version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: billing-db-production
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${BILLING_DB_PASSWORD}
      - MYSQL_DATABASE=${BILLING_DB_NAME}
      - MYSQL_TCP_PORT=${BILLING_DB_PORT}
    volumes:
      - billing-data:/var/lib/mysql
      - ./billing-service/data/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${BILLING_DB_PASSWORD}"]
      interval: 20s
      timeout: 5s
      retries: 5

  billing-service:
    build: ./billing-service
    container_name: billing-service-prod
    ports:
      - "8081:5001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENV=production
      - DB_HOST=db
      - DB_USER=${BILLING_DB_USER}
      - DB_PASSWORD=${BILLING_DB_PASSWORD}
      - DB_NAME=${BILLING_DB_NAME}
      - DB_PORT=${BILLING_DB_PORT}
      - WEIGHTS_PORT=${WEIGHTS_PORT}
      - APP_PORT=${APP_PORT}
      - WEIGHTS_HOST=weight-service
    volumes:
      - ./billing-service/data/in:/app/in
    networks:
      - prod-network
    restart: unless-stopped

  weight-db:
    image: mysql:8.0
    container_name: weight_db_prod
    env_file:
      - .env
    volumes:
      - weight-data:/var/lib/mysql
      - ./weight-service/DB/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"
    networks:
      - prod-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  weight-service:
    build: ./weight-service
    container_name: weight-service-prod
    ports:
      - "8082:5000"
    depends_on:
      weight-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./weight-service/in:/app/in
    networks:
      - prod-network
    restart: unless-stopped

  # ---test runner 
  test-runner:
    build: ./tests
    container_name: test-runner
    depends_on:
      - weight-service
      - weight-db
      - billing-service
      - db
    volumes:
      - ./tests:/tests
    command: ["/bin/sh", "/tests/init.sh"]
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  billing-data:
    driver: local
  weight-data:
    driver: local
