services:
  weight-app:
    build: ./Weight_service
    volumes:
      - ./Weight_service/in:/app/in
  billing-service:
    build: ./billing-service
    volumes:
      - ./billing-service/data/in:/app/in
  weight-db:
    volumes:
      - ./Weight_service/DB:/docker-entrypoint-initdb.d
  db:
    volumes:
      - ./billing-service/data/init:/docker-entrypoint-initdb.d