services:
  weight-db:
    env_file:
      - .env
    volumes:
      - ./Weight_service/DB/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  weight-app:
    build: ./Weight_service
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      weight-db:
        condition: service_healthy
